apiVersion: v1
kind: Service
metadata:
  name: ads
  namespace: governance
  labels:
    app: ads
spec:
  type: ClusterIP
  selector:
    app: ads
  ports:
    - name: bff
      port: 8443
      targetPort: bff
      protocol: TCP
    - name: health
      port: 9090
      targetPort: health
      protocol: TCP
